#+TITLE: separate
* Change action by system environment
  =separate= provide function that help you to separate setting
  by system environment, such as system-name given by =(system-name)=,
  Emacs version, OS, and so on.
* Variables
** =separate-separator-alist=
   - An associated list. Each element is cons cell,
     =(symbol . separator)=. In this package, you can use the =symbol=
     as the =separator=.
* Macros
** =separate-set (variable alist)=
   - Set value of =VARIABLE= depend on =SEPARATOR= below.
   - Each element of =ALIST= is =(SEPARATOR . VALUE)=, and =VARIABLE= is set to =VALUE=
     if =SEPARATOR= is valid.
   - If there are some cons cells whose car (= =SEPARATOR=) is valid, upstream element
     is used, and rest of them is not evaluated.
   - in the cons cell whose =SEPARATOR= is =default=, its =VALUE= is used only when any
     other =SEPARATOR= isn't valid.
** =separate-setq (variable alist)=
   Same as separate-set, but =VARIABLE= doesn't have to be quoted.
** =separate-cond (clauses)=
   - Similar to =cond=, but use =SEPARATOR= instead of =CANDICATE=.
     If =SEPARATOR= is valid, evaluate =BODY=.
   - Priority of each clause is same as =separate-set=.
* License
  This package is licensed by GPLv3. See [[file:LICENSE][LICENSE]].
