#+TITLE: pc-separate
* Change action by pc system
  =pc-separate= provide function that help you to separate setting
  by system name given by =(system-name)=. 
* Words
  -  =system= means system-name or symbol which is defined in =pc-separate-system-alist=.
* Variables
** =pc-separate-system-alist=
   an associated list. Each element is cons cell,
   =(system-name . number-or-symbol)=. in this package, you can use
   =number-or-symbol= as =system= instead of =system-name=.
* Macros
** =pc-separate-set (variable alist)=
   - Set value of =VARIABLE= depend on =system=.
   - Each element of =ALIST= is =(SYSTEM . VALUE)=, and =VARIABLE= is set to =VALUE=
     if =SYSTEM= accords current system.
   - If there are some cons cells whose car accords current system, =number-or-symbol=
     defined on upper stream in =pc-separate-system-alist= is used. System-name is the 
     lowest priority.
   - in the cons cell whose =SYSTEM= is =default=, its =VALUE= is used only when any
     other =SYSTEM= doesn't accord current system.
** =pc-separate-setq (variable alist)=
   Same as pc-separate-set, but =VARIABLE= doesn't have to be quoted.
** =pc-separate-cond (clauses)=
   - Similar to =cond=, but use =SYSTEM= instead of =CANDICATE=.
     If =SYSTEM= accords current system, evaluate =BODY=.
   - Priority of =SYSTEM= is same as =pc-separate-set=.
