#+TITLE: separate
* Change action by pc system
  =separate= provide function that help you to separate setting
  by system name given by =(system-name)=. 
* Words
  -  =system= means system-name or symbol which is defined in =separate-system-alist=.
* Variables
** =separate-system-alist=
   an associated list. Each element is cons cell,
   =(system-name . number-or-symbol)=. in this package, you can use
   =number-or-symbol= as =system= instead of =system-name=.
* Macros
** =separate-set (variable alist)=
   - Set value of =VARIABLE= depend on =system=.
   - Each element of =ALIST= is =(SYSTEM . VALUE)=, and =VARIABLE= is set to =VALUE=
     if =SYSTEM= accords current system.
   - If there are some cons cells whose car accords current system, =number-or-symbol=
     defined on upper stream in =separate-system-alist= is used. System-name is the 
     lowest priority.
   - in the cons cell whose =SYSTEM= is =default=, its =VALUE= is used only when any
     other =SYSTEM= doesn't accord current system.
** =separate-setq (variable alist)=
   Same as separate-set, but =VARIABLE= doesn't have to be quoted.
** =separate-cond (clauses)=
   - Similar to =cond=, but use =SYSTEM= instead of =CANDICATE=.
     If =SYSTEM= accords current system, evaluate =BODY=.
   - Priority of =SYSTEM= is same as =separate-set=.
* License
  This package is licensed by GPLv3. See [[file:LICENSE][LICENSE]].
